name: translator1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "image/translate.png"




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
